### PR TITLE
Added French language regarding issue #44

### PR DESCRIPTION
**Pull request by anupeshverma**
Converted message language from English to French regarding issue #44

### CODE REVIEW

**Comment by anupeshverma** [comment]
Can you please verify this PR and merge it and please add Hacktoberfest Label 🥺

**Comment by Rutuj-Runwal** [comment]
Hi Anupesh, Thank you for your interest in the project.
Currently we are only accepting language translations from native speakers of that language. So you can make a PR for Indian languages listed in Google's list. You can check out and improve the translations of Indian languages in the list.

Thanks.

**Comment by anupeshverma** [comment]
tf

**Comment by anupeshverma** [comment]
Now  please verify this PR and merge it and please add Hacktoberfest Label

**Comment by Rutuj-Runwal** [comment]
> Now  please verify this PR and merge it and please add Hacktoberfest Label

Good work
Kindly create a new PR for the same
Closing this one

Thanks

**Pull request closed without merging**
