### PR TITLE
Safari compatibility

### PR DESCRIPTION
**Pull request by b5i**
Here is the makefile to compile for Safari: juste type `make` for macOS and `make ios` for iOS and iPadOS.
Issue #10

### CODE REVIEW

**Comment by Rutuj-Runwal** [comment]
Hi,
The makefile looks good.
Currently I don't have a system to test and build can you compile.and add it to safari then test it, share a video of the same if possible?

**Comment by b5i** [comment]
By typing `make` you get:
Capture d’écran 2022-10-02 à 10 50 00 AM
Then you double-click (make sure that unsigned extensions are activated in Safari):
Capture d’écran 2022-10-02 à 11 00 26 AM
Then you authorise all websites and your get:
Capture d’écran 2022-10-02 à 11 12 57 AM

**Comment by Rutuj-Runwal** [comment]
> By typing `make` you get: Capture d’écran 2022-10-02 à 10 50 00 AM Then you double-click (make sure that unsigned extensions are activated in Safari): Capture d’écran 2022-10-02 à 11 00 26 AM Then you authorise all websites and your get: Capture d’écran 2022-10-02 à 11 12 57 AM

Great job 
Can you just share the build folder as zip.
I will add it to the release so that users can access it.

**Comment by b5i** [comment]
Sure!
[safari-extension-build.zip](https://github.com/Rutuj-Runwal/RR-Adblocker/files/9692124/safari-extension-build.zip)

**Comment by Rutuj-Runwal** [comment]
Thanks you for your contribution

**Pull request merged**
